config/routes.rb
Rails.application.routes.draw do
  root 'locations#index'
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user

  validate :geo_locate_validation

  def data_missing?
    longitude && latitude ? false : true
  end

  def geo_locate_validation
   ip_reg = /^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
   zip_reg = /^\d{5}(?:[-\s]\d{4})?$/
   unless ip_reg.match?(ip_address) || zip_reg.match?(zip)
    errors.add(:ip_address, :format) unless ip_reg.match?(ip_address)
    errors.add(:zip, :format) unless zip_reg.match?(zip)
   end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :latitude, :longitude

  has_many :locations
  
  geocoded_by :ip,
    latitude: :latitude, longitude: :longitude
  after_find :geocode

  def primary_location
    locations.find_by(primary: true)
  end

  def other_locations
    locations.where(primary: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user

  private

  def set_user
    return if @current_user = User.find_by(ip: request.remote_ip)

    @current_user = User.create(ip: request.remote_ip)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location
  helper_method :set_weather_data

  # GET /locations or /locations.json
  def index
    @locations = @current_user.other_locations
  end

  # GET /locations/1 or /locations/1.json
  def show
    set_weather_data(@location)
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = @current_user.locations.new(location_params)

    unless @location.save
      render partial: '/shared/error', locals: {object: @location}
      return
    end

    if @location.zip.present?
      @location.update(GeoLocate.call(@location.zip))
    elsif @location.ip_address.present?
      @location.update(GeoLocate.call(@location.ip_address))
    end
    set_weather_data(@location)
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_weather_data(location)
    @weather_data = WeatherData.call(location.latitude, location.longitude).reject{ |d| d[:start_time].hour < 6 }
    @weather_chart_data = {high: [], low: []}
    @weather_data.map{ |w| @weather_chart_data[w[:high_low].to_sym] << {w[:start_time].to_date => w[:temp] } }
    @weather_calendar_data = @weather_data.group_by{ |w| w[:start_time].to_date }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      puts 'setting location'
      return if @location = Location.find(params[:id] || @current_user.primary_location.id)

      puts 'creating location'
  
      @location = Location.create(user: @current_user, primary: true, latitude: @current_user.latitude, longitude: @current_user.longitude)
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:ip_address, :address_1, :address_2, :city, :state, :zip, :country, :latitude, :longitude, :primary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhetherTheWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="bootstrap_toast_stream"></div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= turbo_frame_tag 'location_form_dialog' do %>
    
  <%= form_with(model: location) do |form| %>
    <div class="modal-header">
      <h5 class="modal-title">Modal title</h5>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <% if location.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>
          <ul>
            <% location.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :ip_address, style: "display: block" %>
        <%= form.text_field :ip_address %>
      </div>

      <div>
        <%= form.label :address_1, style: "display: block" %>
        <%= form.text_field :address_1 %>
      </div>

      <div>
        <%= form.label :address_2, style: "display: block" %>
        <%= form.text_field :address_2 %>
      </div>

      <div>
        <%= form.label :city, style: "display: block" %>
        <%= form.text_field :city %>
      </div>

      <div>
        <%= form.label :state, style: "display: block" %>
        <%= form.text_field :state %>
      </div>

      <div>
        <%= form.label :zip, style: "display: block" %>
        <%= form.text_field :zip %>
      </div>

      <div>
        <%= form.label :country, style: "display: block" %>
        <%= form.text_field :country %>
      </div>

      <div>
        <%= form.label :latitude, style: "display: block" %>
        <%= form.text_field :latitude %>
      </div>

      <div>
        <%= form.label :longitude, style: "display: block" %>
        <%= form.text_field :longitude %>
      </div>
      <% if !form.object.primary %>
        <div>
          <%= form.label :primary, style: "display: block" %>
          <%= form.check_box :primary %>
        </div>
      <%end%>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <%end%>
<%end%>

app/views/locations/_location.html.erb
<%= turbo_frame_tag "location_#{@location.id}" do %>
  <div class="card">
    <div class="card-body">
      <div class="row align-items-start">
        <% @weather_calendar_data.each do |k,d| %>
          <div class="col">
            <div class="card">
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><%= k %></li>
                <% d.each do |t| %>
                  <li class="list-group-item"><%= t[:high_low] %>: <%= t[:temp].to_s + t[:temp_unit] %><br /><%= t[:condition] %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>

      <div>
        <%= link_to "Edit this location", edit_location_path(@location), data: { turbo_frame: 'location_form_dialog', controller: 'bootstrap--modal', action: 'bootstrap--modal#pop', 'bootstrap--modal-modal-id-value': '#locationModal' }, class: 'btn btn-primary' %>

        <% if !@location.primary %>
          <%= button_to "Delete Location", @location, method: :delete, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<%#= line_chart @weather_chart_data %>

app/views/locations/create.turbo_stream.erb
<turbo-stream action="append", target="locations">
  <template>
    <%= render @location %>
  </template>
</trubo-stream>

app/views/locations/edit.html.erb
<%= render "form", location: @location %>

app/views/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hello <%= @current_user.name || @current_user.ip %></h1>

<% if @location.data_missing? %>
  <div class="card">
    <div class="card-body">
      Sorry I can't seem to find where you are located
    </div>
  </div>
<% else %>
  <%= turbo_frame_tag "location_#{@location.id}", src: location_path(@location), loading: :lazy %>
<% end %>

<div id="locations" class="row">
  <div class="col">
    <% @locations.each do |loc| %>
      <% set_weather_data(loc) %>
      <%= turbo_frame_tag "location_#{loc.id}", src: location_path(id: loc.id), loading: :lazy %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= link_to 'Add Location', new_location_path(), class: "btn btn-primary", data: { turbo_frame: 'location_form_dialog', controller: 'bootstrap--modal', action: 'bootstrap--modal#pop', 'bootstrap--modal-modal-id-value': '#locationModal' } %>
  </div>
</div>

<div class="modal fade" id="locationModal" tabindex="-1">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content">
      <%= turbo_frame_tag "location_form_dialog", scr: new_location_path  %>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<%= render "form", location: @location %>

app/views/locations/show.html.erb
 <%= render @location %>

app/views/shared/_error.turbo_stream.erb
<% object.errors.full_messages.each do |message| %>
  <turbo-stream action="append" target="bootstrap_toast_stream">
    <template>
      <div class="toast align-items-center text-bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
          <div class="toast-body">
            <%= message %>
          </div>
          <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
      </div>
  </template>
<% end %>